[package]
name = "cafmerge"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
quick-xml = "0.22.0"
clap = "3.0.0-beta.2"
git2 = "0.13.20"

[profile.release]
lto = true
panic = 'abort'
